name: Android CI/CD via Bitrise

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  release:
    types: [published]

jobs:
  validate:
    name: Validate Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Permission to Execute Gradle
        run: chmod +x ./gradlew

      - name: Run Lint Checks
        run: ./gradlew lint
        continue-on-error: true

      - name: Run Unit Tests
        run: ./gradlew test

  trigger-bitrise:
    name: Trigger Bitrise Build
    needs: validate
    runs-on: ubuntu-latest

    steps:
      - name: Call Bitrise API to Start Build
        run: |
          curl -X POST "https://api.bitrise.io/v0.1/apps/${{ secrets.BITRISE_APP_SLUG }}/builds" \
          -H "Authorization: ${{ secrets.BITRISE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "hook_info": { "type": "bitrise" },
            "build_params": {
              "branch": "main",
              "workflow_id": "deploy"
            },
            "triggered_by": "GitHub Actions"
          }'

      - name: Wait for Bitrise Build to Complete
        run: |
          BITRISE_BUILD_URL="https://api.bitrise.io/v0.1/apps/${{ secrets.BITRISE_APP_SLUG }}/builds"
          while true; do
            STATUS=$(curl -s -H "Authorization: ${{ secrets.BITRISE_API_TOKEN }}" "$BITRISE_BUILD_URL" | jq -r '.data[].status_text')
            echo "Current Bitrise Build Status: $STATUS"
            if [[ "$STATUS" == "success" ]]; then
              echo "Bitrise Build Succeeded!"
              exit 0
            elif [[ "$STATUS" == "failed" ]]; then
              echo "Bitrise Build Failed!"
              exit 1
            fi
            sleep 30
          done

  release:
    name: Deploy Release (Tag Push)
    if: startsWith(github.ref, 'refs/tags/')
    needs: trigger-bitrise
    runs-on: ubuntu-latest

    steps:
      - name: Call Bitrise API for Release
        run: |
          curl -X POST "https://api.bitrise.io/v0.1/apps/${{ secrets.BITRISE_APP_SLUG }}/builds" \
          -H "Authorization: ${{ secrets.BITRISE_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{
            "hook_info": { "type": "bitrise" },
            "build_params": {
              "branch": "main",
              "workflow_id": "release"
            },
            "triggered_by": "GitHub Actions"
          }'
